#
- include_vars: jenkins-plugins.yml
#----------------------
jenkins_name: jenkins
jenkins_user: jenkins
jenkins_group: jenkins
#----------------------
jenkins_configuration: /etc/default/jenkins
jenkins_home_dir: /var/lib/jenkins              # Jenkins home location
jenkins_root_dir: /usr/share/jenkins            # Location of jenkins arch indep files
jenkins_pid_dir: /var/run
jenkins_cache_dir: /var/cache/jenkins
jenkins_work_dir: /opt/work
#----------------------
jenkins_war: "{{jenkins_root_dir}}/jenkins.war"
jenkins_client: {{jenkins_cache_dir}}/war/WEB-INF/jenkins-cli.jar
#----------------------
jenkins_http_host: "{{ansible_hostname}}"   # Set HTTP host
jenkins_http_port: 8000                     # Set HTTP port
jenkins_prefix: "/"
jenkins_url: http://{{jenkins_http_host}}:{{jenkins_http_port}}{{jenkins_prefix}}
#----------------------
jenkins_maxopenfiles: 65535                 # Increase files limit
jenkins_ssh_key_file: ""                    # Set private ssh key for Jenkins user (path to local file)
#----------------------
jenkins_java: /usr/bin/java
jenkins_java_args:
  - "-Djava.awt.headless=true"
  - "-Xmx256m"
#----------------------
jenkins_system_config:
  admin_email: nobody@example.com
#----------------------
jenkins_log_dir: /var/log/jenkins            # Jenkins logs location
jenkins_logrotate: yes                      # Rotate Jenkins logs.
jenkins_logrotate_options:
  - compress
  - copytruncate
  - daily
  - dateext
  - rotate 7
  - size 10M
#----------------------

