---
#
- name: CentOS | Add Nginx repo
  sudo: yes
  yumrepo:
    name: nginx
    description: Nginx stable Repository
    baseurl: http://nginx.org/packages/{{ ansible_distribution|lower }}/{{ ansible_distribution_version.split('.')[0] }}/$basearch/
    gpgkey: http://nginx.org/keys/nginx_signing.key
    gpgcheck: yes
    enabled: yes
#
- name: CentOS | Install nginx from yum repository
  sudo: yes
  yum:
    name=nginx
    state=latest
#
