---
# file: roles/nginx/tasks/conf_dirs.yml
#
- name: Nginx | Set the right directory permissions for the www directory
  sudo: yes
  file:
    path={{ nginx_www_dir }}
    owner={{ nginx_user }}
    group={{ nginx_group }}
    mode=0755
    state=directory
#
#
#- name: Nginx | Make sure the nginx sites-available directory exists
#  sudo: yes
#  file:
#    path={{ nginx_dir }}/sites-available
#    owner=root
#    group=root
#    mode=0755
#    state=directory
#
#- name: Nginx | Make sure the nginx sites-enabled directory exists
#  sudo: yes
#  file:
#    path={{ nginx_dir }}/sites-enabled
#    owner=root
#    group=root
#    mode=0755
#    state=directory
#
#- name: Update the default site configuration
#  template: src=default.site.j2 dest={{ nginx_dir }}/sites-available/default owner=root group=root mode=0644

#- name: Enable the default site
#  file: path={{ nginx_dir }}/sites-enabled/default src={{ nginx_dir }}/sites-available/default state=link
