---
#
- include: install_packages.yml
#
- include: uninstall_packages.yml
#
- include: create_workspace.yml
#
- include: disable_ipv6.yml
#
- name: Change /etc/host
  sudo: yes
  template:
    src=hosts.j2
    dest=/etc/hosts
    owner=root
    group=root
    mode=0644
#

