---
#
- name: install deps (Ubuntu)
  sudo: yes
  apt: >
    pkg={{ item }}
    state=latest
  with_items:
    - unzip
    - jq
  when: ansible_os_family == "Debian"

- name: install deps (RHEL)
  sudo: yes
  yum: >
    pkg={{ item }}
    state=latest
  with_items:
    - unzip
    - jq
  when: ansible_os_family == "RedHat"
#
- include: common.yml
#
- include: service_install.yml
#
- include: server.yml
#
- include: web-ui.yml
#

