---
#
- name: copy consul upstart script
  sudo: yes
  template: >
    src=consul_upstart.j2
    dest=/etc/init/consul.conf
    owner={{ consul_user }}
    group={{ consul_group }}
    mode=0755
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14") or (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")
  notify:
    - restart consul
#
- name: copy consul systemd script
  sudo: yes
  template: >
    src=consul_systemd.j2
    dest=/etc/systemd/system/consul.service
    owner={{ consul_user }}
    group={{ consul_group }}
    mode=0755
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "15") or (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
  notify:
    - reload systemd
    - restart consul

#- name: copy consul init.d script
# sudo: yes
#  template: >
#    src=consul_initd.j2
#    dest=/etc/init.d/consul
#    owner={{ consul_user }}
#    group={{ consul_group }}
#    mode=0755
#  when: consul_use_initd
#  notify:
#    - restart consul
#
#- name: Enable Consule Agent init script
#  sudo: yes
#  service:
#    name=consul
#    enabled=yes
#
- name: add consul to path through profile.d
  sudo: yes
  template: >
    src=consul.sh.j2
    dest=/etc/profile.d/consul.sh
    owner=root
    group=root
    mode=0755
#
