---
#
- name: Ensure Apache is installed
  sudo: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - httpd
#
- name: Install PHP support if needed
  sudo: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - php
    - php-xml
#  when: httpd_scripting is defined and httpd_scripting == "php"
#
- name: Ensure Apache is always running
  sudo: yes
  service:
    name: httpd
    state: started
    enabled: yes
 #
- include: configure-RedHat.yml
#
#
#- name: Install mod_ssl configuration file
#  template:
#    src: ssl.conf.j2
#    dest: /etc/httpd/conf.d/ssl.conf
#    owner: root
#    group: root
#    setype: httpd_config_t
#    mode: '0644'
#  notify: restart httpd
#
