---
#
# Hostname is important as we need to delete an anonymous MySQL
# user that is created with this name, make sure you match this
# up with the output of the command 'hostname' on the server.
server_hostname: 'example.com'

# vsftpd
vsftpd_anonymous_enable: 'NO'
vsftpd_local_enable: 'YES'
vsftpd_write_enable: 'YES'
vsftpd_local_umask: '002'
