---
#
- name: Zabbix | Add Zabbix repository
  sudo: yes
  yum:
    name={{ zabbix_repo_rhel7 }}
    state=present
#
- name: Zabbix | Install Zabbix agent
  sudo: yes
  yum:
    name=zabbix-agent
    state=present
#
- name: configure /etc/zabbix/zabbix_agentd.conf
  sudo: yes
  template:
    dest=/etc/zabbix/zabbix_agentd.conf
    src=zabbix_agentd.conf.j2
    owner=root
    group=zabbix
    mode=0640
#
- name: ensure started zabbix-agent
  sudo: yes
  service:
   name=zabbix-agent
   state=started
   enabled=yes
#
- include: add_2_zabbix-server.yml
#
