---
#
- name: "Install | packages required for MySQL"
  sudo: yes
  yum:
    pkg={{ item }}
    state=present
  with_items:
	   - "{{ mysql_packages }}"
  notify:
    - start mysqld
#
- name: mysql | Update root password for all root accounts
  mysql_user:
    name={{ mysql_server_root_login }}
    host={{ item }}
    check_implicit_admin=yes
    password={{ mysql_server_root_password }}
    login_user={{ mysql_server_root_login }}
    login_password={{ mysql_server_root_password }}
  with_items:
    - "{{ ansible_fqdn }}"
    - 127.0.0.1
    - localhost
  notify:
    - stop mysqld
#
- name: "INFO | Configure MySQL /etc/my.cnf"
  sudo: yes
  template:
  	src=my.cnf.j2
	dest=/etc/my.cnf
	mode=0644
	owner=root
	group=root
  notify:
    - start mysqld
#
- include: ping_mysqld_server.yml
#

