---
- name: "INFO | Ping MySQL server"
  shell: chdir=/tmp
         mysqladmin --host {{mysql_bind_address}}
                    --port {{mysql_bind_port}}
                    --protocol=TCP
                    --user={{mysql_server_root_login}}
                    --password={{mysql_server_root_password}}
                    ping
  register: if_mysqld_ping
#
- name: "INFO | Alert if MySQL server is not pinged"
  fail: msg="ERROR | Something wrong! I can't connect to the MySQL server!"
  when: not "if_mysqld_ping|success"
#

