---
# file: roles/nodejs/tasks/main.yml
#
- include: ubuntu.yml
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]
#
- include: centos.yml
  when: ansible_distribution in [ 'CentOS', 'RedHat' ]
#
#- include: source_install.yml
#  when: nodejs_install_method == "source"
