---
#
- name: Install dependencies pakages
  sudo: yes
  apt:
    name={{ item }}
    update_cache=yes
    state=latest
  with_items:
    - build-essential
#    - libssl-dev
#
- name: Add -> NodeJS Repository Key
  sudo: yes
  apt_key:
    url="https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state=present
#
- name: Add -> NodeJS Repository
  sudo: yes
  apt_repository:
    repo='deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main'
    update_cache=yes
#
- name: Install NodeJS pakages
  sudo: yes
  apt:
    name=nodejs
    state=latest
#
