---
#
- name: Download -> TrueCrypt
  get_url:
    url=http://sourceforge.net/projects/truecrypt/files/TrueCrypt/Other/{{ true_crypt_package }}
    dest=/tmp/{{ true_crypt_package }}
    mode=0440
#
- name: Extract -> TrueCrypt
  unarchive:
    src=/tmp/{{ true_crypt_package }}
    dest=/tmp
    copy=no
    mode=0770
#
- name: Install -> TrueCrypt
  sudo: yes
  command:
    truecrypt-7.2-setup-x64
#


