---
#
- name: CentOS | Disable SELinux
  sudo: yes
  selinux:
    state: disabled
#
- name: CentOS | Add CentOS docker repo
  sudo: yes
  yumrepo:
    name: docker
    description: Docker Repository
    baseurl: https://yum.dockerproject.org/repo/main/{{ ansible_distribution | lower() }}/{{ ansible_distribution_major_version }}
    gpgcheck: yes
    gpgkey: https://yum.dockerproject.org/gpg
    enabled: yes
#
- name: CentOS | Install -> Docker on CentOS
  sudo: yes
  yum:
    name={{ item }}
    state=latest
    update_cache=yes
  with_items:
    - docker-engine
    - docker-python
#
- name: CentOS | Configure docker unit
  sudo: yes
  template:
    src=docker.service.j2
    dest=/lib/systemd/system/docker.service
    mode=0644
  register: unit
#
- name: CentOS | Reload systemd
  sudo: yes
  command: systemctl daemon-reload
  when: unit|changed
#
