---
#
#- name: Create -> Graph Storage Dir
#  sudo: yes
#  file:
#    path={{ docker_graph_storage_dir }}
#    state=directory
#    mode=0700
#
- include: centos.yml
  when: ansible_distribution in [ 'CentOS', 'RedHat' ]
#
- include: ubuntu.yml
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]
#
- name: ensure started docker-server
  sudo: yes
  service:
   name=docker
   state=started
   enabled=yes
#
- name: Install -> docker-py
  sudo: yes
  pip: name=docker-py
#
- name: Install -> Docker-Compose
  sudo: yes
  get_url:
    url=https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
    dest=/usr/local/bin/docker-compose
    mode=0755
#

