---
#
- name: Download -> Google Chrome
  get_url:
    url=https://dl.google.com/linux/direct/{{ google_chrome_package }}
    dest=/tmp/{{ google_chrome_package }}
    mode=0440
#
- name: Install -> Google Chrome
  sudo: yes
  apt:
    deb=/tmp/{{ google_chrome_package }}
#
