---
#
- name: Disable -> IPv6 on all ethX
  sudo: yes
  sysctl:
    name="net.ipv6.conf.all.disable_ipv6"
    value=1
    sysctl_set=yes
    reload=no
  ignore_errors: true
#
- name: Disable -> IPv6 on default ethX
  sudo: yes
  sysctl:
    name="net.ipv6.conf.default.disable_ipv6"
    value=1
    sysctl_set=yes
    reload=no
  ignore_errors: true
#
- name: Disable -> IPv6 on lo
  sudo: yes
  sysctl:
    name="net.ipv6.conf.lo.disable_ipv6"
    value=1
    sysctl_set=yes
    reload=no
  ignore_errors: true
 #

