---
# file: roles/timezone/tasks/main.yml
- name: Symlink the correct localtime - pt.1
  sudo: yes
  file:
    path=/etc/localtime
    state=absent
#
- name: Symlink the correct localtime - pt.2 (/etc/localtime)
  sudo: yes
  file:
    src=/usr/share/zoneinfo/{{ timezone }}
    dest=/etc/localtime
    state=link
    owner=root
    group=root
    mode=0644
#
- name: Timezone | Configure the ntp servers (/etc/ntp.conf)
  sudo: yes
  template:
    src=ntp.conf.j2
    dest=/etc/ntp.conf
    backup=yes
#
- include: centos.yml
  when: ansible_distribution in [ 'CentOS', 'RedHat' ]
#
- include: ubuntu.yml
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]
#

