# CentOS 7
- name: Install -> Docker on CentOS 7
  yum:
    name=docker
    state=latest
  when: ansible_distribution_version.split('.')[0]|int == 7

- name: Change -> SystemD docker.service config
  lineinfile:
    dest=/lib/systemd/system/docker.service
    regexp=^ExecStart=
    line="ExecStart=/usr/bin/docker -d --graph={{docker_graph_storage_dir}} -H fd://"
  notify:
    - restart docker
  when: ansible_distribution_version.split('.')[0]|int == 7

# CentOS >=6.5
- name: Uninstall -> Graphic applet docker from Docker on CentOS >=6.5
  yum:
    name=docker
    state=absent
  when: ansible_distribution_version.split('.')[0]|int == 6 and ansible_distribution_version.split('.')[1]|int >= 5

- name: Install -> Docker on CentOS >=6.5
  yum:
    name=docker-io
    state=latest
  when: ansible_distribution_version.split('.')[0]|int == 6 and ansible_distribution_version.split('.')[1]|int >= 5

- name: Change -> InitD /etc/default/docker config
  lineinfile:
    dest=/etc/sysconfig/docker-storage
    regexp=^DOCKER_STORAGE_OPTIONS=
    line='DOCKER_STORAGE_OPTIONS="--graph={{docker_graph_storage_dir}}" -H fd://'
  notify:
    - restart docker
  when: ansible_distribution_version.split('.')[0]|int == 6 and ansible_distribution_version.split('.')[1]|int >= 5
