---
#
- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
#
- include: centos.yml
  when: ansible_distribution == "CentOS"
#
- name: Restart vsftpd
  service:
    name=vsftpd
    state=restarted
    enabled=yes
#
