---
#
- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
#
- include: centos.yml
  when: ansible_distribution == "CentOS"
#
- name: FTP | Configuration setup
  template:
    src=vsftpd-conf.j2
    dest=/etc/vsftpd.conf
    owner=root
    group=root
    mode=0644
#
- name: Restart vsftpd
  service:
    name=vsftpd
    state=restarted
    enabled=yes
#
