---
#
# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
#
- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'
#
# Make sure Jenkins starts, then configure Jenkins.
- name: Ensure Jenkins is started and runs on startup.
  sudo: yes
  service:
    name=jenkins
    state=started
    enabled=yes
#
- name: Register Jenkins service
  sudo: yes
  template:
    src=jenkins-default.j2
    dest={{ jenkins_configuration }}
  notify:
    - Restart Jenkins
#
- name: "Configure log rotation"
  sudo: yes
  template:
    src=logrotate.conf.j2
    dest=/etc/logrotate.d/jenkins
#
#- include: ssh.yml
#
- include: plugins.yml
#
