---
- name: Ensure dependencies are installed.
  yum:
    pkg=curl
    state=installed

- name: Ensure Jenkins repo is installed.
  get_url:
    url: "{{ jenkins_repo_url_redhat }}"
    dest: /etc/yum.repos.d/jenkins.repo

- name: Add Jenkins repo GPG key.
  rpm_key:
    key: "{{ jenkins_repo_key_url_redhat }}"
    state: present

- name: Ensure Jenkins is installed.
  yum:
    pkg=jenkins
    state=installed
