---
#
- name: "Install | packages required for mariadb"
  sudo: yes
  yum:
    pkg={{ item }}
    state=present
  with_items:
    - "{{ mariadb_packages }}"
  notify:
    - start mariadb
#
- name: Ensure anonymous users are not in the database
  mysql_user:
    name=''
    host={{ item }}
    state=absent
  with_items:
    - localhost
    - "{{ ansible_fqdn }}"
#
- name: mariadb | Update root password for all root accounts
  mysql_user:
    name={{ mariadb_server_root_login }}
    host={{ item }}
    check_implicit_admin=yes
    password={{ mariadb_server_root_password }}
    login_user={{ mariadb_server_root_login }}
    login_password={{ mariadb_server_root_password }}
  with_items:
    - "{{ ansible_fqdn }}"
    - 127.0.0.1
    - localhost
  notify:
    - stop mariadb
#
- name: "INFO | Configure mariadb /etc/my.cnf"
  sudo: yes
  template:
    src=my.cnf.j2
    dest=/etc/my.cnf
    mode=0644
    owner=root
    group=root
  notify:
    - start mariadb
#
- include: ping_mariadb_server.yml
#

